version: '2'

services:
  cluster:
    image: daocloud.io/redis
    container_name: redis-cluster
    # 添加该参数后服务后台运行后，容器不会自动退出
    tty: true
    restart: always
    # 必须使用host模式，否则容器
    # network_mode: host
    networks:       
      work_net:
        ipv4_address: 172.20.0.4
    volumes:
      - ./data:/data
      - ./config:/etc/redis  
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    ## 必须使用宿主机ip 作为集群总线ip，否则宿主机无法访问到容器内的redis集群ip 
    #  --cluster-announce-ip 172.16.65.218 
    command: 
      - /bin/bash 
      - -c 
      - |
        redis-server /etc/redis/redis_cluster_7000.conf  & 
        redis-server /etc/redis/redis_cluster_7001.conf  &
        redis-server /etc/redis/redis_cluster_7002.conf  &
        redis-server /etc/redis/redis_cluster_7003.conf  & 
        redis-server /etc/redis/redis_cluster_7004.conf  &
        redis-server /etc/redis/redis_cluster_7005.conf  

networks:
  work_net:
    external: true