version: '2'

services:
  redis:
    restart: always
    image: daocloud.io/redis
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - /Users/jeng/tanxinzheng-repo/docker-repo/docker-image-data/docker-redis/data:/data