version: '2'

services:
  redis-stander:
    image: daocloud.io/redis
    container_name: redis-stander
    # 添加该参数后服务后台运行后，容器不会自动退出
    tty: true
    restart: always
    # 必须使用host模式，否则容器
    # network_mode: host
    networks:       
      work_net:
        ipv4_address: 172.20.0.4
    volumes:
      - ./config:/etc/redis
    ports:
      - "6379:6379"
    command: 
      - /bin/bash 
      - -c 
      - |
        mkdir -p /var/lib/redis &
        redis-server /etc/redis/redis.conf

networks:
  work_net:
    external: true