version: '2'

services:
  redis:
    restart: always
    image: daocloud.io/redis
    container_name: local-redis
   # newwork_mode 与network不能同时存在
   # network_mode: bridge
    ports:
      - "6379:6379"
    volumes:
      - /Users/jeng/tanxinzheng-repo/docker/docker-image-demo/docker-redis/data:/data
      - /Users/jeng/tanxinzheng-repo/docker/docker-image-demo/docker-redis/conf/redis.conf:/etc/redis/redis.conf
    networks:
      - local_net
networks:
  local_net:
    external:
      name: app_net