version: '2'

services:
  nginx-download:
    restart: always
    container_name: local-download
    networks:     
      work_net:
        ipv4_address: 172.20.0.10
    image: tanxinzheng/nginx
    ports:
      - "1080:80"
    volumes:
      - ./download:/usr/share/nginx/html/download
      - ./config/nginx.conf:/etc/nginx/nginx.conf


networks:
  work_net:
    external: true
