version: '2'

services:

  portainer:
    restart: always
    image: portainer/portainer
    container_name: "portainer-app"
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /Users/jeng/tanxinzheng-repo/docker-repo/docker-image-data/docker-portainer/data:/data
    ports:
      - "1000:9000"

  watchtower:
    restart: always
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
