version: '2'

services:

  portainer:
    restart: always
    image: portainer/portainer
    container_name: "portainer-app"
    networks:
      work_net:
        ipv4_address: 172.20.0.25
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/docker-portainer/data:/data
    ports:
      - "9000:9000"

  watchtower:
    restart: always
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      work_net:
        ipv4_address: 172.20.0.26
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  work_net:
    external: true
