version: '3.3'

services:

  sonarqube:
    image: sonarqube
    #restart: always
    networks:
      work_net:
        ipv4_address: 172.20.0.19
    ports:
      - 9100:9000
      - 9192:9092
    volumes:
      - data:/opt/sonarqube/data
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:mysql://39.98.252.178:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance&useSSL=false

volumes:
    data: {}


networks:
  work_net:
    external: true