version: '3.3'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - $PWD/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: sonar
      POSTGRES_USER: sonar

  sonarqube:
    image: sonarqube
    #restart: always
    ports:
      - 9100:9000
      - 9192:9092
    volumes:
      - /Users/jeng/tanxinzheng-repo/docker/docker-image-data/docker-postgresql/sonar2:/opt/sonarqube/data
   depends_on:
      - postgresql
    environment:
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: postgres
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql/sonar