version: '3.3'

services:

  sonarqube:
    image: sonarqube
    #restart: always
    ports:
      - 9100:9000
      - 9192:9092
    volumes:
      - data/sonar2:/opt/sonarqube/data
    environment:
      SONARQUBE_JDBC_USERNAME: postgres
      SONARQUBE_JDBC_PASSWORD: postgres
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgresql/sonar