version: '3'

services:
  postgresql:
    image: postgres:9.6.2
    container_name: postgresql
    # networks:
    #   - local_net
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /Users/jeng/tanxinzheng-repo/docker/docker-image-data/docker-postgresql/data:/var/lib/postgresql/data/pgdata
# networks:
#   local_net:
#     external:
#       name: app_net