version: '2'

services:
  griffin:
    image: apachegriffin/griffin_spark2:0.3.0
    hostname: griffin
    links:
      - es
    environment:
      ES_HOSTNAME: es
    volumes:
      - /var/lib/mysql
    ports:
      - 32122:2122
      - 38088:8088  # yarn rm web ui
      - 33306:3306  # mysql
      - 35432:5432  # postgres
      - 38042:8042  # yarn nm web ui
      - 39083:9083  # hive-metastore
      - 38998:8998  # livy
      - 38080:8080  # griffin ui
    tty: true
    container_name: griffin
  es:
    image: apachegriffin/elasticsearch
    hostname: es
    ports:
      - 39200:9200
      - 39300:9300
    container_name: es