version: '2'
services:
  xxljob:
    image: docker.io/xuxueli/xxl-job-admin:2.2.0
    container_name: xxljob
    ports:
      - 21001:8080
    environment:
      TZ: Asia/Shanghai
      PARAMS: '--spring.datasource.url=jdbc:mysql://39.98.252.178:3306/xxl_job?Unicode=true&characterEncoding=UTF-8 --spring.datasource.username=xxljob_data --spring.datasource.password=Shortness#5pale#9Jockstrap#Grows'
    networks:
      work_net:
        ipv4_address: 172.20.0.12
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  work_net:
    external: true